### ISSUE TITLE
mixer/singularity folder empty

### ISSUE THREAD

**Issue by EleniFri** [comorment/mixer#17]
Hi,
When I clone the comorment/containers folder with the command:

git clone --depth 1 https://github.com/comorment/containers.git

there is no subfolder mixer/ in it. If I try to clone the comorment/mixer.git using:

git clone --recurse-submodules -j8 https://github.com/comorment/mixer.git

a singularity/ folder is cloned but remains empty. How can I clone the mixer.sif container?

Thank you

**Comment by espenhgn** [comment]
Hi @EleniFri, 
You don't need the `containers` repository anymore to run these MiXer codes; only the https://github.com/comorment/mixer one:
`git clone --depth 1 https://github.com/comorment/mixer.git`

 Make sure that you have the [git LFS](https://git-lfs.com) extension in order to fetch the `mixer.sif` file correctly. The file is >1GB in size

**Comment by EleniFri** [comment]
Thank you,
In fact, I have both installed and activated git LFS and cloned the comorment/mixer.git, but the singularity folder is still empty. 
Also, I noticed that munge.py says it is version 1.2 in the log file. Does this mean I should be using summary statistics?

**Comment by EleniFri** [comment]
Yes, that could have been it. I was usung git-lfs/2.13.2, thank you! I ran mixer without the container in the meantime.

**Comment by espenhgn** [comment]
Closing, sounds like the issue was resolved. Request to reopen if not.
